### ISSUE TITLE
Geolocation does not work on FF or Safari

### ISSUE THREAD

**Issue by davidjamesknight** [davidjamesknight/miami211#10]
Error: PositionError { code: 1, message: "User denied geolocation prompt" }

This appears even when the user allows geolocation.

Relevant Firefox docs: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

Version: Firefox Dev Edition 52.0a2 (2017-01-20)

**Comment by davidjamesknight** [comment]
I've implemented a workaround by making geolocation/"search by address" optional and defaulting to a generic downtown Miami address.

**Comment by ErnieAtLYD** [comment]
We weren't able to replicate it on my OSX, FF or Safari as they all requested browser access to the Geolocation API. We think David has a super high privacy browser.
